### ISSUE TITLE
Add some badges?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/opentracksapp.github.io#4]
https://img.shields.io/github/v/tag/OpenTracksApp/OpenTracks

https://img.shields.io/f-droid/v/de.dennisguse.opentracks.svg

https://img.shields.io/liberapay/gives/OpenTracks

https://img.shields.io/github/issues/OpenTracksApp/OpenTracks

https://img.shields.io/github/license/OpenTracksApp/OpenTracks

**Comment by mattbk** [comment]
You probably want https://img.shields.io/liberapay/receives/OpenTracks for Liberapay, to show what the project is receiving.

**Comment by dennisguse** [comment]
@mattbk Already there :)
It is in the menu and loads rather slowly...
We use: https://img.shields.io/liberapay/receives/opentracks.svg?logo=liberapay
